version: "2"
linters:
  settings:
    revive:
      rules:
        - name: exported
          disabled: true

  enable:
    - goconst
    - unconvert
    - gosec
    - revive
    - unparam
    - gocyclo
