version: 1
timeout: '1m'

validators:
  # randomly it returns the error: status code 403: Forbidden
  - regex: 'groups\.google\.com'
    type: 'ignore'
  # somehow stackoverflow is returning also a status code 403
  - regex: 'stackoverflow\.com'
    type: 'ignore'
  # context timeout
  - regex: 'mui\.com'
    type: 'ignore'
  # code 500
  - regex: 'slack\.com'
    type: 'ignore'
  # code 502
  - regex: 'storybook\.js\.com'
    type: 'ignore'
  # timeout
  - regex: 'tanstack\.com'
    type: 'ignore'
  # timeout
  - regex: 'github\.com'
    type: 'ignore'
  # timeout
  - regex: 'slack\.cncf\.io'
    type: 'ignore'
  # timeout
  - regex: 'nodejs\.org'
    type: 'ignore'
  # timeout
  - regex: 'youtube\.com'
    type: 'ignore'
  # timeout
  - regex: 'lodash\.com'
    type: 'ignore'