version: 1
timeout: '1m'

validators:
  # randomly it returns the error: status code 403: Forbidden
  - regex: 'groups\.google\.com'
    type: 'ignore'
  # somehow stackoverflow is returning also a status code 403
  - regex: 'stackoverflow\.com'
    type: 'ignore'
