FROM node:25 AS node-builder
WORKDIR /app
COPY ui ui
COPY Makefile Makefile
RUN make build-ui

FROM golang:1.25 AS go-builder
WORKDIR /go/src/github.com/perses/perses
COPY . .
COPY --from=node-builder /app/ui/app/dist ui/app/dist
RUN mkdir /perses \
  && mkdir /plugins \
  && make build-api \
  && make build-cli

FROM gcr.io/distroless/static-debian12:nonroot

LABEL maintainer="The Perses Authors <perses-team@googlegroups.com>"

COPY --from=go-builder                          /go/src/github.com/perses/perses/bin/perses        /bin/perses
COPY --from=go-builder                          /go/src/github.com/perses/perses/bin/percli        /bin/percli
COPY                                            LICENSE            /LICENSE
COPY --from=go-builder --chown=nonroot:nonroot  /go/src/github.com/perses/perses/plugins-archive/   /etc/perses/plugins-archive/
COPY                                            docs/examples/config.docker.yaml     /etc/perses/config.yaml
COPY --from=go-builder --chown=nonroot:nonroot  /perses            /perses
COPY --from=go-builder --chown=nonroot:nonroot  /plugins           /etc/perses/plugins
COPY --from=go-builder                          /etc/mime.types    /etc/mime.types

WORKDIR /perses

EXPOSE     8080
VOLUME     ["/perses"]
ENTRYPOINT [ "/bin/perses" ]
CMD        ["--config=/etc/perses/config.yaml", \
            "--log.level=error"]
