FROM node:20 AS node-builder
WORKDIR /app
COPY ui ui
COPY Makefile Makefile
RUN make build-ui

FROM golang:1.24 AS go-builder
WORKDIR /go/src/github.com/perses/perses
COPY . .
COPY --from=node-builder /app/ui/app/dist ui/app/dist
RUN mkdir /perses
RUN mkdir /plugins
RUN make build-api
RUN make build-cli

FROM gcr.io/distroless/static-debian12

LABEL maintainer="The Perses Authors <perses-team@googlegroups.com>"

USER nobody

COPY --from=go-builder --chown=nobody:nobody  /go/src/github.com/perses/perses/bin/perses        /bin/perses
COPY --from=go-builder --chown=nobody:nobody  /go/src/github.com/perses/perses/bin/percli        /bin/percli
COPY --chown=nobody:nobody                    LICENSE            /LICENSE
COPY --chown=nobody:nobody                    plugins-archive/   /etc/perses/plugins-archive/
COPY --chown=nobody:nobody                    docs/examples/config.docker.yaml     /etc/perses/config.yaml
COPY --from=go-builder --chown=nobody:nobody  /perses            /perses
COPY --from=go-builder --chown=nobody:nobody  /plugins           /etc/perses/plugins
COPY --from=go-builder --chown=nobody:nobody  /etc/mime.types    /etc/mime.types

WORKDIR /perses

EXPOSE     8080
VOLUME     ["/perses"]
ENTRYPOINT [ "/bin/perses" ]
CMD        ["--config=/etc/perses/config.yaml", \
            "--log.level=error"]
