database:
  file:
    folder: "./perses"
    extension: "json"

schemas:
  panels_path: "./cue/schemas/panels"
  queries_path: "./cue/schemas/queries"
  datasources_path: "./cue/schemas/datasources"
  variables_path: "./cue/schemas/variables"
  interval: "6h"
