database:
  file:
    folder: "./perses"
    extension: "json"

schemas:
  panels_path: "./schemas/panels"
  queries_path: "./schemas/queries"
  datasources_path: "./schemas/datasources"
  variables_path: "./schemas/variables"
  interval: "5m"
