// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/perses/perses/pkg/model/api/v1/search

package search

import "github.com/perses/perses/cue/model/api"

// MatchingInterval represents the start and the end position of the continuous characters that is matching the pattern.
// For example, for the pattern `bc`, with the string `abcd`, the corresponding interval will be [{from: 1, to: 2}]
// Another example, for the pattern `fuz`, with the string `fzduzf`, the corresponding intervals will be:
// [ { from: 0, to: 0 }, { from: 3, to: 4 } ]
#MatchingInterval: {
	from: uint64 @go(From)

	// To is always superior to From
	to: uint64 @go(To)
}

#Result: {
	// Metadata is the metadata of the resource that matches the query.
	metadata: api.#Metadata @go(Metadata)

	// DisplayName is the string that will be used for the search display.
	displayName: string @go(DisplayName)

	// The original string that matches the query.
	original: string @go(Original)

	// The list of intervals that match the query.
	intervals: [...#MatchingInterval] @go(Intervals,[]MatchingInterval)

	// Score is the score of the match, the higher the score, the better the match.
	// When there is a perfect match, then the number is infinite.
	score: uint64 @go(Score)
}

#Query: {
	Project: string
	Query:   string
}
