// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/perses/perses/pkg/model/api/v1

package v1

#DatasourceInterface: _

// GlobalDatasource is the struct representing the datasource shared to everybody.
// Any Dashboard can reference it.
#GlobalDatasource: _

// Datasource will be the datasource you can define in your project/namespace
// This is a resource that won't be shared across projects.
// A Dashboard can use it only if it is in the same project.
#Datasource: _
