// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/perses/perses/pkg/model/api/v1

package v1

#FolderDisplay: {
	name?: string @go(Name)
}

// FolderItem is a single node in the folder tree. Kind is either "Dashboard" or "Folder".
// When Kind is "Folder", Items holds the nested children.
#FolderItem: _

#FolderSpec: {
	display?: null | #FolderDisplay @go(Display,*FolderDisplay)
	items?: [...#FolderItem] @go(Items,[]FolderItem)
}

#Folder: _
