// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/perses/perses/pkg/model/api/v1

package v1

// Health is the struct that provides the health information of the API
#Health: {
	buildTime: string @go(BuildTime)
	version:   string @go(Version)
	commit:    string @go(Commit)
	database:  bool   @go(Database)
}
