// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/perses/perses/pkg/model/api/v1

package v1

#PartialEntity: {
	kind:     #Kind     @go(Kind)
	metadata: #Metadata @go(Metadata)
	spec?: {} @go(Spec,struct{})
}

#PartialProjectEntity: {
	kind:     #Kind            @go(Kind)
	metadata: #ProjectMetadata @go(Metadata)
	spec?: {} @go(Spec,struct{})
}
