// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/perses/perses/pkg/model/api/v1

package v1

import "github.com/perses/perses/cue/model/api/v1/plugin"

#PluginModuleKind: "PluginModule"

#PluginModule: {
	kind:     string                 @go(Kind)
	metadata: plugin.#ModuleMetadata @go(Metadata)
	spec:     plugin.#ModuleSpec     @go(Spec)
}
