// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/perses/perses/pkg/model/api/v1

package v1

import "github.com/perses/spec/cue/common"

#ProjectSpec: {
	display?: null | common.#Display @go(Display,*common.Display)
}

#Project: _
