// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/perses/perses/pkg/model/api/v1

package v1

import "github.com/perses/perses/cue/model/api/v1/secret"

#PublicUserSpec: {
	firstName?: string         @go(FirstName)
	lastName?:  string         @go(LastName)
	password?:  secret.#Hidden @go(Password)
}

#PublicUser: {
	kind:     #Kind           @go(Kind)
	metadata: #Metadata       @go(Metadata)
	spec:     #PublicUserSpec @go(Spec)
}
