// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/perses/perses/pkg/model/api/v1

package v1

#RoleBindingInterface: _

#Subject: _

#RoleBindingSpec: _

// GlobalRoleBinding is the struct representing the roleBinding shared to everybody.
#GlobalRoleBinding: _

// RoleBinding will be the roleBinding you can define in your project/namespace
// This is a resource that won't be shared across projects.
#RoleBinding: _
