// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/perses/perses/pkg/model/api/v1

package v1

#SecretSpec: _

#GlobalSecret: {
	kind:     #Kind       @go(Kind)
	metadata: #Metadata   @go(Metadata)
	spec:     #SecretSpec @go(Spec)
}

#Secret: {
	kind:     #Kind            @go(Kind)
	metadata: #ProjectMetadata @go(Metadata)
	spec:     #SecretSpec      @go(Spec)
}
