// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/perses/perses/pkg/model/api/v1

package v1

#WildcardProject: "*"

#NativeProvider: {
	password?: string @go(Password)

	// PasswordHash accepts a pre-computed bcrypt hash instead of a plaintext password.
	// When set, the hash is stored directly without re-hashing.
	// This is useful for provisioning users from configuration files without exposing
	// cleartext passwords (e.g. in Kubernetes ConfigMaps).
	// Mutually exclusive with Password.
	passwordHash?: string @go(PasswordHash)
}

#OAuthProvider: {
	issuer?:  string @go(Issuer)
	email?:   string @go(Email)
	subject?: string @go(Subject)
}

#UserSpec: {
	firstName?:      string          @go(FirstName)
	lastName?:       string          @go(LastName)
	nativeProvider?: #NativeProvider @go(NativeProvider)
	oauthProviders?: [...#OAuthProvider] @go(OauthProviders,[]OAuthProvider)
}

#User: _
