// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/perses/perses/pkg/model/api/v1

package v1

#UserSpec: {
	firstName?: string @go(FirstName)
	lastName?:  string @go(LastName)
	password?:  string @go(Password)
}

#User: _
