// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/perses/perses/pkg/model/api/v1

package v1

import "github.com/perses/perses/cue/model/api/v1/role"

// WatchEvent is emitted by the watch SSE endpoint to notify backend resource changes.
#WatchEvent: {
	kind:    #Kind        @go(Kind)
	project: string       @go(Project)
	name:    string       @go(Name)
	action:  role.#Action @go(Action)
}
