// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/perses/perses/pkg/model/api/v1/datasource/http

package http

#AllowedEndpoint: _

#Config: _

#Proxy: {
	kind: string  @go(Kind)
	spec: #Config @go(Spec)
}

#ProxyKindName: "httpproxy"
