version: 2
builds:
  - id: "perses"
    main: ./cmd/perses/main.go
    binary: "perses"
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - "{{.Env.LDFLAGS}}"
  - id: "percli"
    main: ./cmd/percli/main.go
    binary: "percli"
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - "{{.Env.LDFLAGS}}"
archives:
  - id: "default"
    ids:
      - "perses"
      - "percli"
    formats:
      - "tar.gz"
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
      - plugins-archive
      - src: "docs/examples/config.archive.yaml"
        dst: "./config.yaml"
release:
  github:
    owner: "perses"
    name: "perses"
  ids:
    - "default"
  prerelease: auto
  name_template: "{{ .Version }} / {{ .Env.DATE }}"
