global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]
  - job_name: 'tempo'
    static_configs:
      - targets: [ 'tempo:3200' ]
  - job_name: 'avalanche'
    static_configs:
      - targets: [ 'avalanche:9001' ]
    metric_relabel_configs:
      # Remove leak on native histograms, maybe others too
      - action: labeldrop
        regex: cycle_id