// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/perses/perses/pkg/model/api/v1/common

package common

// Display
// DEPRECATED: this is replaced by the struct github.com/perses/spec/go/common.Display
#Display: {
	name?:        string @go(Name)
	description?: string @go(Description)
}
