// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/perses/perses/pkg/model/api/v1/common

package common

#PluginMetadata: {
	// Version is optional. If not provided, it means the latest version available in the Perses instance.
	version?: string @go(Version)

	// Registry is optional. If not provided, it means the default registry: "perses.dev".
	registry?: string @go(Registry)
}

#Plugin: _
