// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/perses/perses/pkg/model/api/v1/common

package common

// Regexp encapsulates a regexp.Regexp and makes it JSON/YAML marshalable.
#Regexp: _
