---
name: Feature request
description: Suggest an idea for this project.
labels: [ "enhancement" ]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for opening a feature request for Perses.

        Please do *NOT* ask support questions in Github issues.

        If your issue is not a feature request or bug report use [Discussions](https://github.com/perses/perses/discussions).
  - type: textarea
    attributes:
      label: Proposal
      description: Use case. Why is this important?
    validations:
      required: true
