// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/perses/perses/pkg/model/api/v1/secret

package secret

// PublicBasicAuth is the public struct of BasicAuth.
// It's used when the API returns a response to a request
#PublicBasicAuth: {
	username:      string  @go(Username)
	password?:     #Hidden @go(Password)
	passwordFile?: string  @go(PasswordFile)
}

#BasicAuth: _
