// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/perses/perses/pkg/model/api/v1/secret

package secret

// The K8sAuth structs are used to save the kubeconfig file location on disk, and and have some
// utilities around loading that file or the information in it for use
#PublicK8sAuth: {
	kubeconfig?: string @go(KubeconfigFile)
}

#K8sAuth: _
