// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/perses/perses/pkg/model/api/v1/secret

package secret

_#secretToken: "<secret>"

// Hidden special type for storing secrets.
#Hidden: _
