// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/perses/perses/pkg/model/api/v1/secret

package secret

#PublicSigV4: {
	region:         string  @go(Region)
	accessKey?:     string  @go(AccessKey)
	secretKey?:     #Hidden @go(SecretKey)
	secretKeyFile?: string  @go(SecretKeyFile)
	roleArn?:       string  @go(RoleARN)
	externalId?:    string  @go(ExternalID)
	serviceName:    string  @go(ServiceName)
}

// SigV4 signs the requests with the AWS Signature Version 4, to query an AWS service.
// When no access key is set, the credentials come from the default credential chain of the Perses server
// (environment, web identity, ECS or EC2 instance metadata), which must be explicitly allowed by the server configuration.
#SigV4: _
