// Copyright The Perses Authors
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// NB: This file complements the sigv4_go_gen.cue file generated by
// `cue get go` to add the missing constraints lost in the translation
// process. This should no longer be needed at some point hopefully, but for
// the moment, because of a technical limitation in the CUE translation
// process, a top-value (= "any") gets generated instead of a proper def for
// any type that defines a custom UnmarshallJSON or UnmarshallYAML.
// For more info see https://github.com/cue-lang/cue/issues/2466.

package secret

#SigV4: {
	// Region is the AWS region of the service, for example us-east-1.
	region: string & !="" @go(Region)

	// AccessKey is the AWS access key ID. It must be set together with SecretKey or SecretKeyFile.
	accessKey?: string @go(AccessKey)

	// SecretKey is the AWS secret access key.
	secretKey?: #Hidden @go(SecretKey)

	// SecretKeyFile is the path to a file containing the AWS secret access key.
	secretKeyFile?: string @go(SecretKeyFile)

	// RoleARN is the ARN of an IAM role to assume before signing the requests.
	roleArn?: string @go(RoleARN)

	// ExternalID is the external ID used to assume the role. It can only be set with RoleARN.
	externalId?: string @go(ExternalID)

	// ServiceName is the name of the AWS service the requests are signed for, for example "monitoring" for CloudWatch.
	serviceName: string & !="" @go(ServiceName)
}
