name: "Setup environment"
description: "Setup GO or NPM environment"
inputs:
  enable_go:
    description: Whether to enable go specific features, such as caching.
    default: "false"
  enable_npm:
    description: Whether to enable npm specific features, such as caching.
    default: "false"
runs:
  using: composite
  steps:
    - name: Install Go
      uses: actions/setup-go@v3
      if: inputs.enable_go == 'true'
      with:
        go-version: 1.19.x
    - uses: actions/cache@v3.0.8
      if: inputs.enable_go == 'true'
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Install nodejs
      uses: actions/setup-node@v3
      if: inputs.enable_npm == 'true'
      with:
        node-version-file: "ui/.nvmrc"
        registry-url: "https://registry.npmjs.org"
    - uses: actions/cache@v3.0.8
      if: inputs.enable_npm == 'true'
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
