apiVersion: v1
kind: Secret
metadata:
  name: {{ include "perses.fullname" . }}
  labels:
    {{- include "perses.labels" . | nindent 4 }}
  {{- with .Values.config.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  config.yaml: |-
    readonly: {{ .Values.config.readOnly }}

    database:
      {{- with .Values.config.database.file }}
      file:
        {{- toYaml . | nindent 8 }}
      {{ end -}}

      {{- with .Values.config.database.sql }}
      sql:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{ end -}}
    
    {{- with .Values.config.important_dashboards }}
    important_dashboards:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    
    {{- with .Values.config.schemas }}
    schemas:
      {{- toYaml . | nindent 6 }}
    {{- end }}

