apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "perses.fullname" . }}
  labels:
    {{- include "perses.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicas }}
  serviceName: {{ include "perses.fullname" . }}-headless
  selector:
    matchLabels:
      {{- include "perses.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "perses.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "perses.serviceAccountName" . }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.name }}:v{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
          - --config=/perses/config/config.yaml
          - --web.listen-address=:{{ .Values.service.targetPort }}
          - --web.hide-port=false
          - --web.telemetry-path=/metrics
          - --log.level={{ .Values.logLevel }}
          - --log.method-trace=true
        volumeMounts:
          - name: config
            mountPath: "/perses/config"
          - name: data
            mountPath: /perses
        ports:
          - name: http
            containerPort: {{ .Values.service.targetPort }}
        readinessProbe:
          httpGet:
            path: /metrics
            port: http
            scheme: HTTP
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
        livenessProbe:
          httpGet:
            path: /metrics
            port: http
            scheme: HTTP
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      volumes:
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "perses.fullname" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: config
          secret:
            secretName: {{ include "perses.fullname" . }}