// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/perses/perses/pkg/model/api/v1/variable

package variable

#TextSpec: {
	display?:  null | #Display @go(Display,*Display)
	value:     string          @go(Value)
	constant?: bool            @go(Constant)
}
