export type Kind =
  | 'Dashboard'
  | 'Datasource'
  | 'Folder'
  | 'GlobalDatasource'
  | 'GlobalRole'
  | 'GlobalRoleBinding'
  | 'GlobalSecret'
  | 'GlobalVariable'
  | 'Project'
  | 'Role'
  | 'RoleBinding'
  | 'Secret'
  | 'User'
  | 'Variable';
