// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/perses/perses/pkg/model/api/v1/dashboard

package dashboard

import "github.com/perses/perses/cue/model/api/v1/variable"

_#variableSpec: _

#TextVariableSpec: _

#ListVariableSpec: _

#Variable: _

_#tmpVariable: {
	kind: variable.#Kind @go(Kind)
	spec: _              @go(Spec,any)
}
