name: Test Collector Chart

on:
  pull_request:
    paths:
      - "charts/perses/**"
    branches:
      - main

jobs:
  collector-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup
        uses: ./.github/actions/setup_helmlint
        with:
          create-kind-cluster: "true"

      - name: Run chart-testing (install)
        run: ct install --charts charts/perses
