name: release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
jobs:
  prepare_release:
    name: "prepare_release"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check Tag
        run: ./ui_release.sh --check-version "${{ github.ref_name }}"
      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version-file: "ui/.nvmrc"
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install UI deps
        run: cd ./ui && npm install
      - name: Build the app
        run: cd ./ui && npm run build
      - name : Check libraries version
        run: ./ui_release.sh --check "${{ github.ref_name }}"
      - name: store react production build
        uses: actions/upload-artifact@v2
        with:
          name: ui-libs
          path: |
            ui/**/dist
            !ui/node_modules

  libs-release:
    name: "prepare_release"
    needs: build-frontend
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version-file: "ui/.nvmrc"
      - name: Download react build
        uses: actions/download-artifact@v2
        with:
          name: ui-libs
      - name: Copy files before publishing libs
        run: ./scripts/ui_release.sh --copy
      - name: Login to npm registry
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
      - name: Publish libraries
        run: ./scripts/ui_release.sh --publish

  go-release:
    name: "go and github release"
    needs: "prepare_release"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Download react build
        uses: actions/download-artifact@v2
        with:
          name: ui-libs
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish Release and binaries
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
